In [84]:
import numpy as np
from math import sqrt

In [2]:
a = np.array((1,2,3))

In [30]:
b = np.array((1,1,1))

In [42]:
np.einsum('i,jk->ik',a,b)

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [35]:
b = np.array(((1,1,1),(1,1,1)))

In [16]:
b

array([[1, 1, 1],
       [1, 1, 1]])

In [19]:
np.linalg.norm(a-b,axis=1)

array([2.23606798, 2.23606798])

In [41]:
b.shape

(2, 3)

In [43]:
b = np.array((1,1,1))

In [47]:
%timeit np.einsum('i,i->i',a,b)

37.6 µs ± 3.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [57]:
%timeit np.ei('i,i',a,b)

72.5 µs ± 3.31 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [75]:
%timeit np.dot(a,b)

955 ns ± 5.3 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [72]:
%timeit np.matmul(a,b)

1.6 µs ± 5.99 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [76]:
%timeit np.vdot(a,b)

827 ns ± 36.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [78]:
%timeit np.linalg.norm(a)

5.23 µs ± 175 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [79]:
%timeit sqrt(np.vdot(a,a))

889 ns ± 11.8 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [80]:
np.dot?

In [81]:
x = np.linspace(0,2*np.pi,100)
y = np.linspace(0,2*np.pi,101)
z = np.linspace(0,2*np.pi,102)

In [83]:
import numba as nb

In [124]:
@nb.autojit
def gen_sinusoidal_normvecs(x,y,z):
    ret = np.empty((x.shape[0],y.shape[0],z.shape[0],3))
    for k in range(z.shape[0]):
        for j in range(y.shape[0]):
            for i in range(x.shape[0]):
                ret[i,j,k,0] = 2*np.cos(2*x[i])*np.sin(2*y[j])
                ret[i,j,k,0] = 2*np.sin(2*x[i])*np.cos(2*y[j])
                ret[i,j,k,2] = -1
                ret[i,j,k] /= math.sqrt(np.sum(ret[i,j,k]**2))
    return ret

def np_gen(x,y,z):
    xi3_sinusoid = np.empty((x.shape[0],y.shape[0],z.shape[0],3))

    xi3_sinusoid[...,0] = 2*np.cos(2*np.meshgrid(x,y,z,indexing='ij')[0])*np.sin(2*np.meshgrid(x,y,z,indexing='ij')[1])
    xi3_sinusoid[...,1] = 2*np.sin(2*np.meshgrid(x,y,z,indexing='ij')[0])*np.cos(2*np.meshgrid(x,y,z,indexing='ij')[1])
    xi3_sinusoid[...,2] = -1
    
    xi3_sinusoid = (xi3_sinusoid.transpose(3,0,1,2) / np.linalg.norm(xi3_sinusoid,axis=3)).transpose(1,2,3,0)
    return xi3_sinusoid

In [120]:
%timeit q = gen_sinusoidal_normvecs(x,y,z)

352 ms ± 6.07 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [112]:
q.shape

(100, 101, 102, 3)

In [125]:
q2 = np_gen(x,y,z)

In [126]:
import math

In [127]:
q2.shape

(100, 101, 102, 3)